# @package _global_
optimizer:
  _target_: torch.optim.Adam
  lr: 0.001

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 100
  gamma: 0.1

module:
  _target_: emg2qwerty.train.TDSConvCTCModule
  in_features: 512  # n_mels=32 * channels=16
  out_features: 768
  block_channels: [24, 24, 24, 24]
  kernel_width: 11
  optimizer: ${optimizer}
  lr_scheduler: ${lr_scheduler}

datamodule:
  _target_: emg2qwerty.train.WindowedEmgDataModule
  batch_size: 8
  num_dataloader_workers: 0
  train_window_length: 10000
  train_window_padding: [1750, 250]
