# @package _global_
module:
  _target_: emg2qwerty.train.TDSConvCTCModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  out_features: 768
  block_channels: [24, 24, 24, 24]
  kernel_width: 32  # Temporal receptive field of 125 samples

datamodule:
  _target_: emg2qwerty.train.WindowedEmgDataModule
  window_length: 8000  # 4 sec windows at 2000Hz
  padding: [1800, 200]  # 900ms past context, 100ms future context
