# conda env create -f environment.yml
name: emg2qwerty
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pytorch::pytorch=2.0.1
  - pytorch::pytorch-cuda=11.7.0
  - pytorch::torchaudio=2.0.2
  - pytorch::torchvision=0.15.2
  - pytorch-lightning>=2.0.9
  - numpy
  - scipy
  - h5py>=3.0
  - python-levenshtein>=0.12.2
  - unidecode
  - pandas
  - pyyaml
  - nltk
  - pytest
  - hypothesis
  - click
  - pre-commit
  - black
  - flake8
  - mypy
  - mne-bids
  - pip
  - pip:
    - hydra-core>=1.1.0
    - hydra-submitit-launcher
    - omegaconf>=2.1.0
    - lightning-bolts
    - https://github.com/kpu/kenlm/archive/master.zip
