# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

trainer:
  num_nodes: 1
  gpus: 8

hydra:
  launcher:
    submitit_folder: ${hydra.sweep.dir}/submitit_logs/%j
    nodes: ${trainer.num_nodes}
    gpus_per_node: ${trainer.gpus}
    tasks_per_node: 1
    cpus_per_task: 40
    mem_gb: 300
    timeout_min: 2880
    partition: learnfair
  run:
    dir: /checkpoint/${oc.env:USER}/emg2qwerty/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: /checkpoint/${oc.env:USER}/emg2qwerty/${now:%Y-%m-%d}/${now:%H-%M-%S}
