# @package _global_

transforms:
  train:
    - _target_: emg2qwerty.transforms.ToTensor
      fields: [emg_left, emg_right]
    - _target_: emg2qwerty.transforms.RandomBandRotation
      offsets: [-1, 0, 1]
    - _target_: emg2qwerty.transforms.TemporalAlignmentJitter
      max_offset: 3
    - _target_: emg2qwerty.transforms.LogMelSpectrogram
      n_fft: 512
      window_length: 160
      stride: 40
      n_mels: 32
    - _target_: emg2qwerty.transforms.SpecAugment
      n_time_masks: 0
      time_mask_param: 0
      n_freq_masks: 0
      freq_mask_param: 0

  val:
    - _target_: emg2qwerty.transforms.ToTensor
      fields: [emg_left, emg_right]
    - _target_: emg2qwerty.transforms.LogMelSpectrogram
      n_fft: 512
      window_length: 160
      stride: 40
      n_mels: 32

  test: ${transforms.val}
