defaults:
  - user: generic
  - transforms: log_spectrogram
  - model: tds_conv_ctc
  - optimizer: adam
  - lr_scheduler: linear_warmup_cosine_annealing

seed: 1501
batch_size: 32
num_workers: 4
metric: val_CER
checkpoint: null

trainer:
  max_epochs: 150
  num_nodes: 1
  gpus: 1

callbacks:
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: ${metric}
    mode: min
    save_last: True
    verbose: True

dataset:
  root: ${hydra:runtime.cwd}/data

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}
  job:
    name: emg2qwerty
    config:
      override_dirname:
        exclude_keys:
          - cluster
